/* Study Buddy built-in guide — English */
AssistantI18n.register("en", {
  greeting: "Hi! I'm Study Buddy 🎓 Ask me about NFST/NOS, required documents, eligibility, applying, payments or complaints. You can also tap 🎤 and speak your question.",
  fallback: "I'm not sure about that one yet — I can help with scheme details (NFST/NOS), documents, eligibility, the application steps, tracking status, payments or complaints. Try one of the topics below, or rephrase your question.",
  placeholder: "Ask a question…",
  privacy: "🔒 For your safety I removed personal numbers (Aadhaar / phone / account) before answering. Please don't share them in chat.",
  hints: [],
  quick: [["NFST vs NOS", "schemes"], ["Documents needed", "documents"], ["Eligibility", "eligibility"], ["How to apply", "apply"], ["Payment status", "payments"], ["Raise complaint", "grievance"]],
  kb: {
    greeting: { k: ["hi", "hello", "hey", "namaste", "yo"], a: "Hi! I'm Study Buddy 🎓 I can help with questions about NFST / NOS, the application steps, required documents, eligibility, and tracking your status. What would you like to know?" },
    schemes: { k: ["scheme", "schemes", "which scholarship", "what scholarship", "options", "nfst vs nos", "nfst and nos", "difference between nfst and nos"], a: "TribalScholar currently lists two schemes:\n\n• NFST — National Fellowship for ST Students (for PhD / research in India)\n• NOS — National Overseas Scholarship (for Master's/PhD study abroad, needs a university offer letter)\n\nAsk me about either one, e.g. \"what is NFST\" or \"eligibility for NOS\"." },
    nfst: { k: ["nfst", "fellowship", "national fellowship", "research"], a: "NFST — National Fellowship for ST Students:\n• For PhD / research-level study in India\n• Requires: ST certificate, marksheet, income certificate\n• Prototype rules: marks ≥ 55%, annual family income ≤ ₹8,00,000\n\nThis is demo logic — always check the official scheme guidelines too." },
    nos: { k: ["nos", "overseas", "study abroad", "national overseas", "abroad"], a: "NOS — National Overseas Scholarship:\n• For Master's or PhD study abroad\n• Requires: ST certificate, marksheet, income certificate, AND a university offer letter\n• Prototype rules: marks ≥ 60%, annual family income ≤ ₹8,00,000\n\nThis is demo logic — check the official NOS guidelines for the real criteria." },
    eligibility: { k: ["eligible", "eligibility", "criteria", "qualify", "income limit", "marks required", "percentage required"], a: "Eligibility (prototype rules) depends on your chosen scheme:\n• NFST: PhD/research level, marks ≥ 55%, income ≤ ₹8,00,000\n• NOS: Master's or PhD, marks ≥ 60%, income ≤ ₹8,00,000, offer letter required\n\nOpen the Apply page, fill the form, and the eligibility check shows a live pass/fail result." },
    documents: { k: ["document", "documents", "upload", "certificate", "papers", "files needed", "what to upload"], a: "You'll typically need:\n• ST Certificate\n• Marksheets / Academic Record\n• Income Certificate\n• University Offer Letter (only for NOS)\n\nUpload a photo/PDF or fetch verified documents from DigiLocker. If an image is blurry the portal will ask you to retake it." },
    apply: { k: ["how to apply", "apply", "start application", "application process", "steps", "form"], a: "Applying is 4 steps:\n1. Log in and pick a scheme\n2. Fill in personal, academic & income details\n3. Upload your documents or fetch them from DigiLocker\n4. Run \"Check My Application\", fix anything flagged, then submit — you'll get an Application ID (e.g. TS260001)" },
    track: { k: ["track", "status", "application id", "where is my application", "application status"], a: "Go to the \"Track Application\" tab and enter your Application ID (e.g. TS260001). You'll see the current status — Submitted, Under Review, Deficient, or Approved — plus a timeline." },
    deficient: { k: ["deficient", "correction", "rejected", "issue with my application", "what went wrong", "fix my application"], a: "\"Deficient\" means the pre-check found an issue — a missing field, a mismatch between your form and document data, or a possibly expired certificate. Track your application and check the 🔔 button for the full notice." },
    payments: { k: ["payment", "money", "amount", "when will i get", "dbt", "pfms", "bank", "disbursement"], a: "After approval the payment goes through 4 stages:\n1. Sanctioned\n2. Payment initiated (PFMS)\n3. DBT processed\n4. Credited to bank account\n\nSee the live status in the \"Payments\" tab. Your bank account must be Aadhaar-linked (NPCI seeding)." },
    grievance: { k: ["grievance", "complaint", "problem", "issue", "help with"], a: "Open the \"Grievance\" tab, choose a category and describe the problem. You'll get a ticket ID, the complaint is routed to the right department, and you can track its resolution." },
    digilocker: { k: ["digilocker", "aadhaar", "ekyc"], a: "On the Apply page press \"Fetch via DigiLocker\", give consent and select your issued ST, income and marksheet documents. These come straight from the issuing department, so they count as verified and the form auto-fills." },
    contact: { k: ["contact", "help desk", "support", "phone number", "email support", "talk to someone", "helpline"], a: "This is a student-built prototype, so there isn't a live support line here. For official queries, contact your scholarship scheme's helpdesk or state nodal office." }
  }
});
